services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html 
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
    # volumes:
    #   - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

# volumes:
#   db_data: